name: generate ASCII artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
    
    - name: List repo files
      run: ls -ltra
    - name: executing shell Script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh
 